## 1. Numpy import 하기

In [1]:
# numpy패키지를 np라는 별칭으로 가져와서 사용한다.
import numpy as np

In [2]:
# import한 패키지의 별칭만 다르게 사용하면 
# 모든 파이썬 패키지의 버전을 확인할수 있다.
print(np.__version__)

1.19.5


In [ ]:
# !는 리눅스 터미널 명령어를 사용할때 붙이는 기호
!pip list

## 2. ndarray 생성하기

In [4]:
arr = np.array([1, 2, 3, 4], dtype=int)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr0 = np.array([1.,2.,3.,4.])
type(arr0)

numpy.ndarray

### 2-1. list로 부터 생성하기

In [9]:
mylist1 = [1, 2, 3, 4]

In [10]:
mylist2 = [[1, 2, 3, 4], 
           [5, 6, 7, 8]]

In [11]:
arr1 = np.array(mylist1)

In [12]:
arr2 = np.array(mylist2)

### 2-2. shape확인하기

In [13]:
# 4행으로 만들어진 array
arr1.shape

(4,)

In [ ]:
arr2.shape

(2, 4)

## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용

### 3-1. list에서의 data 타입

In [14]:
mylist = [1, 3.14, 'hello', '1234']

In [15]:
mylist

[1, 3.14, 'hello', '1234']

In [ ]:
mylist[1]

3.14

In [ ]:
mylist[2]

'hello'

### 3-2. array에서의 data 타입이 혼재된 경우

### int와 float 타입이 섞인 경우

In [16]:
arr = np.array([1, 2, 3, 3.14])

In [17]:
arr

array([1.  , 2.  , 3.  , 3.14])

### int와 float 타입이 섞인 경우, dtype을 지정한 경우

In [18]:
arr = np.array([1, 2, 3, 3.14], dtype=int)

In [19]:
arr

array([1, 2, 3, 3])

### int와 float, str 타입이 혼재된 경우

In [20]:
arr = np.array([1, 3.14, 'abc', '1234'])

In [21]:
arr

array(['1', '3.14', 'abc', '1234'], dtype='<U32')

In [ ]:
arr[0] + arr[1]

'13.14'

### int와 str 타입이 혼재된 경우, int로 dtype을 지정한 경우

In [23]:
temp = '1234'
value = int(temp)
type(value)

int

In [ ]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [ ]:
    arr

array([   1,    3, 1234])